# Compose file for launching the peer service dev setup with
# 3 peers :D but no couchDB :-(

version: '2'

networks:
    grainchainnet:

# Storage for containers
volumes:
  data-peer1.grainchain.io:
  data-peer2.grainchain.io:
        

services:
# Harvx peer1
  peer1.grainchain.io:
    container_name: peer1.grainchain.io
    image: hyperledger/fabric-peer:2.1.1
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_grainchainnet
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - /vagrant/peer/config:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - /vagrant/ca/client/config/crypto-config/peerOrganizations/harvx.io/peers/peer1.grainchain.io/msp:/var/hyperledger/msp  
      # Added to support the TLS setup
      #- ${PWD}/config/crypto-config/peerOrganizations/acme.io/peers/peer1.acme.io/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.grainchain.io:/var/hyperledger/production
      - /vagrant/bin:/var/hyperledger/config/scripts
      #gopath
      - /vagrant/gopath:/opt/gopath
    # depends_on: 
    #   - orderer.acme.io
    # Map the ports on Host VM to container ports
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      - grainchainnet

  # Harvx peer2
  # harvx-peer2.grainchain.io:
  #   container_name: harvx-peer2.grainchain.io
  #   image: hyperledger/fabric-peer:2.1.1
  #   # Override variables in this section
  #   environment:
  #     - FABRIC_CFG_PATH=/var/hyperledger/config
  #     - FABRIC_LOGGING_SPEC=WARNING
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_grainchainnet
  #   # Start the peer node
  #   command: peer node start
  #   # Host folder mappings
  #   volumes:
  #     # Folder with channel create tx file
  #     - /vagrant/peer/config:/var/hyperledger/config
  #     # Map the folder with MSP for Peer
  #     - /vagrant/config/crypto-config/peerOrganizations/grainchain.io/peers/peer2.grainchain.io/msp:/var/hyperledger/msp
  #     # Added to support the TLS setup
  #     #- ${PWD}/config/crypto-config/peerOrganizations/acme.io/peers/peer1.acme.io/tls:/var/hyperledger/tls
  #     - /var/run/:/var/run/
  #     - data-harvx-peer2.grainchain.io:/var/hyperledger/production
  #     - /vagrant/bin:/var/hyperledger/config/scripts
  #     - /vagrant/gopath:/opt/gopath
  #   # depends_on: 
  #   #   - orderer.acme.io
  #   # Map the ports on Host VM to container ports
  #   ports:
  #     - 8051:7051
  #     - 8052:7052
  #   networks:
  #     - grainchainnet
